default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: demo_vconstruct_development

test:
  <<: *default
  database: demo_vconstruct_test

production:
  <<: *default
  database: demo_vconstruct_production
  username: demo_vconstruct
  password: <%= ENV['DEMO_VCONSTRUCT_DATABASE_PASSWORD'] %>
